### ISSUE TITLE
Undefined array key "contentHtml" then editing tag notice is present

### ISSUE THREAD

**Issue by taravasya** [datlechin/flarum-bbcode-hide-content#1]
Hello! Looks like i`m first issuer ))
Then I confirm discussion tag editing an error occurs:
_Oops! Something went wrong. Please reload the page and try again._

And in debug this:
```
POST http://flarum.taravasya/api/discussions/966

<br />
<b>Warning</b>:  Undefined array key "contentHtml" in <b>D:\SYNCPROJECTS\FLARUM\vendor\datlechin\flarum-bbcode-hide-content\src\HideContentInPosts.php</b> on line <b>25</b><br />
<br />
<b>Fatal error</b>:  Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php:24
Stack trace:
#0 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent()
#1 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;assertNoPreviousOutput()
#2 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter-&gt;emit(Object(Flarum\Api\JsonApiResponse))
#3 D:\SYNCPROJECTS\FLARUM\vendor\flarum\core\src\Http\Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner-&gt;run()
#4 D:\SYNCPROJECTS\FLARUM\public\index.php(26): Flarum\Http\Server-&gt;listen()
#5 {main}
  thrown in <b>D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php</b> on line <b>24</b><br />
```
After refreshin page its just white screen with: 
```
Warning: Undefined array key "contentHtml" in D:\SYNCPROJECTS\FLARUM\vendor\datlechin\flarum-bbcode-hide-content\src\HideContentInPosts.php on line 25

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php:24 Stack trace: #0 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Emitter\SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(Laminas\Diactoros\Response\HtmlResponse)) #3 D:\SYNCPROJECTS\FLARUM\vendor\flarum\core\src\Http\Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 D:\SYNCPROJECTS\FLARUM\public\index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in D:\SYNCPROJECTS\FLARUM\vendor\laminas\laminas-httphandlerrunner\src\Exception\EmitterException.php on line 24
```
(seems to be the same error )
This error come up only on previously edited discussion. All others are functioning normally.

Looks like problem is in this notice:
![image](https://user-images.githubusercontent.com/7197473/175653575-90af0213-6dbd-4051-baa9-d15f3fadcb50.png)

---
 - I dissable extension.
 - Successfully reload discussion
 - Delete this notice with corresponding option:
![image](https://user-images.githubusercontent.com/7197473/175655885-289ab014-dc12-4b7c-b8e8-bab6dc021d24.png)
 - ReEnable extension
 - Refresh and get working discussion page with no errors

**Comment by datlechin** [comment]
Thank you, I’ll take a look
